### ISSUE TITLE
Importing a scrapy project?

### ISSUE THREAD

**Issue by vishalvsparrow** [h4t0n/instagram-scraper#4] opened 2018-08-21 19:02 UTC
I am new to Scrapy, and ran into an error where the command "crawl" was not found. Turns out that I had to create a project first with a .cfg file

The work-around for this that I used was to run a self-contained spider using the command `scrapy runspider hashtag.py` after renaming the parent directory to "scrapy_instagram"

What would be a correct way to import a scrapy project ?

**Comment by h4t0n** [comment] 2018-08-22 19:57
Duplicate of #2

**Closed as completed by h4t0n** 2018-08-22 19:57 UTC
